apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synology-csi-driver-client-info
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  data:
  - secretKey: client-info.yml
    remoteRef:
      key: synology-csi-driver-client-info
      property: client-info.yml
