apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger-operator
spec:
  project: default
  source:
    chart: jaegertracing/jaeger-operator
    repoURL: https://jaegertracing.github.io/helm-charts
    targetRevision: 2.57.0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: jaeger-operator
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
