apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lapi-hotel-system
spec:
  destination:
    namespace: lapi-hotel-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s
    repoURL: https://github.com/dragoneena12/lapi-hotel-system
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
