apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onepassword-connect
spec:
  project: default
  source:
    chart: connect
    repoURL: https://1password.github.io/connect-helm-charts/
    targetRevision: 1.15.0
    helm:
      valuesObject:
        connect:
          tls:
            enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: onepassword-connect
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
