apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-operator
spec:
  project: default
  source:
    path: k8s/opentelemetry-operator
    repoURL: https://github.com/dragoneena12/lapi-infra
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
