apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: synology-csi-driver
spec:
  project: default
  source:
    chart: synology-csi
    repoURL: https://christian-schlichtherle.github.io/synology-csi-chart
    targetRevision: v1.1.3
    helm:
      valuesObject:
        clientInfoSecret:
          create: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: synology-csi-driver
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
