apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: synology-csi-driver-config
spec:
  project: default
  source:
    path: k8s/synology-csi-driver-config
    repoURL: https://github.com/dragoneena12/lapi-infra
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: synology-csi-driver
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
