apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: synology-csi-driver
spec:
  project: default
  source:
    chart: synology-csi
    repoURL: https://christian-schlichtherle.github.io/synology-csi-chart
    targetRevision: 0.9.8
    helm:
      valuesObject:
        clientInfoSecret:
          create: false
        # TODO: https://github.com/christian-schlichtherle/synology-csi-chart/pull/18 これがマージされたら消す
        volumeSnapshotClasses:
          delete:
            deletionPolicy: Delete
  destination:
    server: "https://kubernetes.default.svc"
    namespace: synology-csi-driver
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
