- name: install k3s
  ansible.builtin.shell: curl -sfL https://get.k3s.io | sh -
  changed_when: False

- name: template setting file
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/rancher/k3s/config.yaml
  register: copy_config_file

- name: restart k3s
  ansible.builtin.systemd:
    state: restarted
    name: k3s
  when: copy_config_file is changed
