apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudprober
spec:
  selector:
    matchLabels:
      app: cloudprober
  template:
    metadata:
      labels:
        app: cloudprober
    spec:
      containers:
      - name: cloudprober
        image: ghcr.io/cloudprober/cloudprober:v0.13.7
        ports:
        - containerPort: 9313
        volumeMounts:
          - name: config
            mountPath: /etc/cloudprober.cfg
            subPath: cloudprober.cfg
      volumes:
      - name: config
        configMap:
          name: cloudprober
---
apiVersion: v1
kind: Service
metadata:
  name: cloudprober
spec:
  selector:
    app: cloudprober
  ports:
  - port: 9313
    targetPort: 9313
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudprober
data:
  cloudprober.cfg: |
    probe {
      name: "furport_prod"
      type: HTTP
      targets {
        endpoint {
          name: "frontend_root"
          url: "https://furport.lapi.tokyo"
        }
        endpoint {
          name: "backend_events"
          url: "https://furport-backend-prod.deno.dev/events"
        }
      }
      latency_unit: "ms"
      latency_distribution:
        exponential_buckets:
          scale_factor: 1
          base: 2
          num_buckets: 15
      interval_msec: 60000
      timeout_msec: 10000
    }
