apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: furport-monitor-jaeger
spec:
  strategy: allInOne # default
  storage:
    type: memory # default
  ingress:
    hosts:
      - furport-jaegar.lapi.tokyo
    tls:
      - hosts:
          - furport-jaegar.lapi.tokyo
        secretName: furport-monitor-jaeger-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
