apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: furport-monitor-jaeger
spec:
  strategy: allInOne # default
  storage:
    type: memory # default
---
apiVersion: v1
kind: Service
metadata:
  name: furport-monitor-jaeger
spec:
  selector:
    app: furport-monitor-jaeger
  ports:
  - port: 4318
    targetPort: 4318
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: furport-monitor-jaeger
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
  - host: furport-jaeger.lapi.tokyo
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: furport-monitor-jaeger
            port:
              number: 4318
  tls:  
  - hosts:
    - furport-jaeger.lapi.tokyo
    secretName: furport-monitor-jaeger-tls
