apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: furport-monitor
spec:
  image: otel/opentelemetry-collector-contrib:0.109.0
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      httpcheck:
        targets:
          - endpoint: https://furport.lapi.tokyo
            method: GET
        collection_interval: 60s

    processors: {}

    exporters:
      debug: {}
      prometheus:
        endpoint: 0.0.0.0:8889
        namespace: default

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [debug]
        metrics:
          receivers: [httpcheck]
          processors: []
          exporters: [prometheus]
