apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: furport-monitor
spec:
  config:
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
      prometheus:
        config:
          scrape_configs:
          - job_name: 'cloudprober'
            static_configs:
            - targets: ['cloudprober:9313']

    processors: {}

    exporters:
      otlp/jaeger:
        endpoint: furport-monitor-jaegar:4318
        tls:
          insecure: true
      prometheus:
        endpoint: 0.0.0.0:8889
        namespace: otlc

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlp/jaeger]
        metrics:
          receivers: [prometheus]
          processors: []
          exporters: [prometheus]
---
apiVersion: v1
kind: Service
metadata:
  name: furport-monitor-otlp
spec:
  selector:
    app: furport-monitor-otlp
  ports:
  - port: 4318
    targetPort: 4318
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: furport-monitor-otlp
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
  - host: furport-otlp.lapi.tokyo
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: furport-monitor-otlp
            port:
              number: 4318
  tls:  
  - hosts:
    - furport-otlp.lapi.tokyo
    secretName: furport-monitor-otlp-tls
