apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: furport-monitor
spec:
  config:
    receivers:
      prometheus:
        config:
          scrape_configs:
          - job_name: 'cloudprober'
            static_configs:
            - targets: ['cloudprober:9313']

    processors: {}

    exporters:
      prometheus:
        endpoint: 0.0.0.0:8889
        namespace: otlc

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: []
          exporters: [prometheus]
