apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: furport-monitor-prometheus
spec:
  selector:
    matchLabels:
      app: furport-monitor-prometheus
  serviceName: furport-monitor-prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: furport-monitor-prometheus
    spec:
      securityContext:
        fsGroup: 2000
        runAsUser: 1000
        runAsNonRoot: true
      containers:
      - name: furport-monitor-prometheus
        image: prom/prometheus:v2.54.1
        ports:
        - containerPort: 9090
          name: http
        volumeMounts:
        - name: data
          mountPath: /prometheus
        - name: config
          mountPath: /etc/prometheus
      volumes:
      - name: config
        configMap:
          name: furport-monitor-prometheus
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: furport-monitor-prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 1m
      evaluation_interval: 1m
    scrape_configs:
    - job_name: 'otlc'
      static_configs:
      - targets: ['furport-monitor-collector:8889']
