apiVersion: v1
kind: ServiceAccount
metadata:
  name: github
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: github
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: sa-token-github
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: github
type: kubernetes.io/service-account-token
